### ISSUE TITLE
Orcaslicer crashing on startup

### ISSUE THREAD

**Issue by satchafunkilus** [helfrichmichael/orcaslicer-novnc#1]
Tried to start the container on Unraid - Orcaslicer seems to be crashing on start. Log files show:

2023-05-12 09:31:08,805 INFO spawned: 'orcaslicer' with pid 108
2023-05-12 09:31:08,882 INFO exited: orcaslicer (exit status 1; not expected)
2023-05-12 09:31:09,884 INFO spawned: 'orcaslicer' with pid 113
2023-05-12 09:31:09,964 INFO exited: orcaslicer (exit status 1; not expected)
2023-05-12 09:31:11,967 INFO spawned: 'orcaslicer' with pid 118
2023-05-12 09:31:12,044 INFO exited: orcaslicer (exit status 1; not expected)
2023-05-12 09:31:15,049 INFO spawned: 'orcaslicer' with pid 123
2023-05-12 09:31:15,125 INFO exited: orcaslicer (exit status 1; not expected)
2023-05-12 09:31:16,126 INFO gave up: orcaslicer entered FATAL state, too many start retries too quickly

**Comment by Karoolus** [comment]
I have the same issue

**Comment by WolfwithSword** [comment]
Same here, with the same logs as OP

**Comment by helfrichmichael** [comment]
Thanks all, can you confirm if you're in the terminal of noVNC, and you run: `/orcaslicer/squashfs-root/AppRun` I assume you get an error relating to "No such file or directory"?

If so I should have a fix after work this evening. Looks like I missed a step in the directory creation and binding.

**Comment by WolfwithSword** [comment]
Yep, running that in the console gives this:

```
[2023-05-12 14:32:07.516719] [0x00001520383ee9c0] [trace]   Initializing StaticPrintConfigs
add font of HarmonyOS_Sans_SC_Bold returns 1
add font of HarmonyOS_Sans_SC_Regular returns 1
[2023-05-12 14:32:07.531789] [0x00001520383ee9c0] [error]   boost::filesystem::create_directory: No such file or directory: "/root/.config/OrcaSlicer"


(process:71): GLib-GObject-WARNING **: 14:32:07.531: invalid (NULL) pointer instance

(process:71): GLib-GObject-CRITICAL **: 14:32:07.531: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

**Comment by helfrichmichael** [comment]
> Yep, running that in the console gives this:
> 
> ```
> [2023-05-12 14:32:07.516719] [0x00001520383ee9c0] [trace]   Initializing StaticPrintConfigs
> add font of HarmonyOS_Sans_SC_Bold returns 1
> add font of HarmonyOS_Sans_SC_Regular returns 1
> [2023-05-12 14:32:07.531789] [0x00001520383ee9c0] [error]   boost::filesystem::create_directory: No such file or directory: "/root/.config/OrcaSlicer"
> 
> 
> (process:71): GLib-GObject-WARNING **: 14:32:07.531: invalid (NULL) pointer instance
> 
> (process:71): GLib-GObject-CRITICAL **: 14:32:07.531: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> ```

Awesome and it is indeed what I suspected. I'll fix this later today then. Thanks for the confirmation!

**Comment by WolfwithSword** [comment]
No problem! I'm just glad to finally have the slicer dockerized with noVNC. Was attempting it a few months ago but had some issues. Will be great to host a shared slicer for my configs to slice remotely + finally have a reliable setup for constant local video stream monitoring!

**Comment by helfrichmichael** [comment]
> No problem! I'm just glad to finally have the slicer dockerized with noVNC. Was attempting it a few months ago but had some issues. Will be great to host a shared slicer for my configs to slice remotely + finally have a reliable setup for constant local video stream monitoring!

Fingers crossed, but the latest version should resolve the issues! Please let me know if there is anything further preventing it from launching (just tested on 2 devices including unraid).
