### ISSUE TITLE
Video Playback not working (missing Gstreamer codec)

### ISSUE THREAD

**Issue by satchafunkilus** [helfrichmichael/orcaslicer-novnc#4]
When trying to view the video stream in the device tab, I get the following error message:
![grafik](https://github.com/helfrichmichael/orcaslicer-novnc/assets/3892444/6ebaaa33-9e8f-4d49-bffe-424b99d2c27a)

**Comment by helfrichmichael** [comment]
Ack. Adding this now.

**Comment by helfrichmichael** [comment]
https://github.com/helfrichmichael/orcaslicer-novnc/commit/00bb00f86340001ab969fd0c926fe78c1c03f70a has been added. Pushing to Docker now.
