### ISSUE TITLE
Latest release not being pulled at compose

### ISSUE THREAD

**Issue by longman391** [helfrichmichael/orcaslicer-novnc#6]
The current latest released version of OrcaSlicer is 1.6.3, but there seems to be an issue in the sh file that grabs the latest version since it only ever returns 1.6.2.

**Comment by kylek29** [comment]
Seems to be from a naming convention change as the script that retrieves the latest info from GitHub calls for "_Linux_ubuntu.zip" but they're now being labeled as "_Linux.zip".

I'm making a pull request to address that.

**Comment by kylek29** [comment]
For those stumbling on this, I created an update script to handle updating without rebuilding the Docker. @helfrichmichael is free to integrate this if he pleases.

File: https://github.com/kylek29/misc_code/blob/main/OrcaSlicer-noVNC-docker/update_orcaslicer.sh

Usage:

1. Download the update_orcaslicer.sh script to somewhere on the Docker. You can put it into your /prints/ folder, as that maybe easiest.
2. Connect to a Console on the Docker (for unRAID that's right-click the icon -> console)
3. Go to where you placed the script and run cmd:   "chmod +x /update_orcaslicer.sh" (no quotes)
4. Run the script:
	./update_orcaslicer.sh -f
	./update_orcaslicer.sh -i
	./update_orcaslicer.sh -v
5. Reboot the Docker.


Available Commands:
-	-f : Fix the get_release_info.sh script so it can retrieve the files again (only need to do it once if the upstream patch isn't merged).
-  -v : Check the currently installed version.
-	-i : Install latest found version.
-   -c: Clean up the old version (probably best to do it after you test it).



![image](https://github.com/helfrichmichael/orcaslicer-novnc/assets/15932180/3080d6d5-54fc-4ef7-84c4-1e6aea2c04c8)

**Comment by helfrichmichael** [comment]
Apologies on the delay here. My notifications were off on mobile for GitHub apparently. I'll try to review and merge tonight. Thanks for this!

**Comment by helfrichmichael** [comment]
It's building and deploying to Docker as we speak. If all is well then we can see what issues remain (if any) for this image. Thanks a ton @kylek29!

**Comment by malkiebr** [comment]
I think this issue is happening again. 1.7.0 is out, but the image is stuck to 1.6.4-beta 2

**Comment by helfrichmichael** [comment]
Sorry for the delay on this. The workflow and action are fixed now!
